version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: clines
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: alura-clines-api
    environment:
      DB_HOST: database
    ports:
      - "8080:8080"
volumes:
  db-volume: